### ISSUE TITLE
Move Repository Classes of Shared Assembly

### ISSUE THREAD

**Issue by thiagocarreno** [Codvanced/framework#64]
Move model classes of repository of assembly "IOC.FW.Shared" to "IOC.FW.Repository".

**Comment by thiagocarreno** [comment]
Is not possible, because this action will create a circular reference.
For this approach, I think better create assembly IOC.FW.Data.

@lcssk8board What do you think ?

**Comment by lcssk8board** [comment]
Why don't we move the Model/Repository classes to the IOC.FW.Repository and leave this for the enumerators and other general use classes?

**Comment by hubvivo** [comment]
Because if we move model of repository of assembly IOC.FW.Shared to IOC.FW.Repository we need the fowlling situation. 

The repository assembly needs abstraction assembly because the abstractions and abstraction assembly needs repository assembly because the model.

I think a good idea move enumerators of shared assembly to another assembly.

**Comment by thiagocarreno** [comment]
Because if we move model of repository of assembly IOC.FW.Shared to IOC.FW.Repository we need the fowlling situation.

The repository assembly needs abstraction assembly because the abstractions and abstraction assembly needs repository assembly because the model.

I think a good idea move enumerators of shared assembly to another assembly.

**Comment by thiagocarreno** [comment]
Issue resolved in issue #92.
